### ISSUE TITLE
Merge into zsh-completions project ?

### ISSUE THREAD

**Issue by nicoulaj** [mqus/zsh-nft-completion#1]
We have a community completions repository [here](https://github.com/zsh-users/zsh-completions), maybe this one could be added?

**Comment by mqus** [comment]
sure but with the disclaimers mentioned in the README file (I'm very much a beginner in zsh and there are some bugs in the script). This is also the main reason I didn't add this to the "official" completions repo. Should I submit a PR anyway?

Obviously, I would be okay with the zsh license.

**Comment by mqus** [comment]
... I just looked over it again and noticed that it could need some cleanup :D

**Comment by nicoulaj** [comment]
Great!

The rules we put in README are quite strict to avoid some bad contributions/copy paste pull requests we get, but in reality the bar is lower in this repo than in zsh itself. For difficult completions functions such as this one it is OK to have something unpolished. We are all beginners :)

Anyway, you can submit a PR, or I can give you committer access (or both), when you feel ready.

**Comment by mqus** [comment]
PR submitted: https://github.com/zsh-users/zsh-completions/pull/609
